import { Box } from "@mui/material";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Lorem ipsum dolor, sit amet consectetur adipisicing elit. Vel obcaecati
      enim repudiandae! Enim, dolores, repudiandae voluptatibus magni quo saepe
      vero eveniet tempore voluptates rerum unde iusto quam, officiis quod ab?
    </>
  );
}
