import { Box, Button } from "@mui/material";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { signOut } from "next-auth/react";

export default function Home() {
  const { data: session } = useSession();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {JSON.stringify(session?.user)}
      <Button onClick={() => signOut({ callbackUrl: "/login" })}>
        Sign out
      </Button>
    </>
  );
}
